/**
 * API Routes Command - Generate _uptrade API proxy routes
 * 
 * Creates the catch-all API route at app/_uptrade/api/[...path]/route.ts
 * that proxies requests to Portal API.
 */

import chalk from 'chalk'
import ora from 'ora'
import fs from 'fs/promises'
import path from 'path'
import { existsSync } from 'fs'

interface ApiRoutesOptions {
  dryRun?: boolean
  force?: boolean
}

export async function apiRoutesCommand(options: ApiRoutesOptions) {
  console.log('')
  console.log(chalk.bold('  Site-Kit API Routes'))
  console.log('')

  // Find app directory
  const appDir = findAppDir()
  if (!appDir) {
    console.log(chalk.red('  ✗ Could not find app directory'))
    console.log(chalk.gray('    Make sure you are in a Next.js project with an app directory'))
    console.log('')
    process.exit(1)
  }

  const routeDir = path.join(appDir, '_uptrade', 'api', '[...path]')
  const routeFile = path.join(routeDir, 'route.ts')

  // Check if already exists
  if (existsSync(routeFile) && !options.force) {
    console.log(chalk.yellow('  ⚠ API routes already exist'))
    console.log(chalk.gray(`    ${routeFile}`))
    console.log('')
    console.log(chalk.gray('    Use --force to overwrite'))
    console.log('')
    return
  }

  if (options.dryRun) {
    console.log(chalk.yellow('  [DRY RUN] Would create:'))
    console.log(chalk.gray(`    ${routeFile}`))
    console.log('')
    return
  }

  // Create directories
  const spinner = ora('Creating API routes...').start()

  try {
    await fs.mkdir(routeDir, { recursive: true })

    // Write the route handler
    await fs.writeFile(routeFile, generateRouteHandler())

    spinner.succeed('Created API proxy routes')
    console.log(chalk.gray(`    ${routeFile}`))
    console.log('')

    console.log(chalk.bold('  Available endpoints:'))
    console.log(chalk.gray('    GET/POST /_uptrade/api/forms/:formId/submit'))
    console.log(chalk.gray('    GET /_uptrade/api/blog'))
    console.log(chalk.gray('    GET /_uptrade/api/locations'))
    console.log(chalk.gray('    GET /_uptrade/api/reviews'))
    console.log(chalk.gray('    ... and more'))
    console.log('')

    console.log(chalk.green('  ✓ API routes ready'))
    console.log('')
  } catch (error: any) {
    spinner.fail(`Failed to create API routes: ${error.message}`)
  }
}

function findAppDir(): string | null {
  const candidates = [
    path.join(process.cwd(), 'app'),
    path.join(process.cwd(), 'src', 'app'),
  ]

  for (const candidate of candidates) {
    if (existsSync(candidate)) {
      return candidate
    }
  }

  return null
}

function generateRouteHandler(): string {
  return `/**
 * Uptrade API Proxy
 * 
 * This route proxies requests to the Uptrade Portal API.
 * It handles authentication and adds the project context.
 * 
 * Generated by @uptrade/site-kit
 */

import { NextRequest, NextResponse } from 'next/server'

const API_URL = process.env.NEXT_PUBLIC_UPTRADE_API_URL || 'https://api.uptrademedia.com'
const API_KEY = process.env.UPTRADE_API_KEY

// Handle all HTTP methods
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ path: string[] }> }
) {
  return handleRequest(request, await params)
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ path: string[] }> }
) {
  return handleRequest(request, await params)
}

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ path: string[] }> }
) {
  return handleRequest(request, await params)
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ path: string[] }> }
) {
  return handleRequest(request, await params)
}

async function handleRequest(
  request: NextRequest,
  params: { path: string[] }
) {
  const { path: pathSegments } = params
  const targetPath = pathSegments.join('/')
  
  const targetUrl = new URL(\`/api/public/\${targetPath}\`, API_URL)
  
  // Copy query params
  request.nextUrl.searchParams.forEach((value, key) => {
    targetUrl.searchParams.set(key, value)
  })

  // Prepare headers
  const headers: HeadersInit = {
    'Content-Type': 'application/json',
  }

  // Add API key if available
  if (API_KEY) {
    headers['x-api-key'] = API_KEY
  }

  // Get body for non-GET requests
  let body: string | undefined
  if (request.method !== 'GET' && request.method !== 'HEAD') {
    try {
      body = await request.text()
    } catch {
      // No body
    }
  }

  try {
    const response = await fetch(targetUrl.toString(), {
      method: request.method,
      headers,
      body,
    })

    const data = await response.json()

    return NextResponse.json(data, {
      status: response.status,
      headers: {
        'Access-Control-Allow-Origin': '*',
      },
    })
  } catch (error: any) {
    console.error('[Uptrade API Proxy]', error)
    return NextResponse.json(
      { error: 'API request failed', message: error.message },
      { status: 500 }
    )
  }
}
`
}
